### ISSUE TITLE
installation of adapter failed 

### ISSUE THREAD

**Issue by minoger** [StefaE/PVOptimize#3]
Hello,

we tried to install the adapter and get the following error (log).

`_npm ERR! premature close_
`

the log shows the following:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '
1 verbose cli ]
2 info using npm@6.14.18
3 info using node@v14.21.3
4 verbose config Skipping project config: /opt/iobroker/.npmrc. (matches userconfig)
5 verbose npm-session f47e5b556ec[19618](tel:19618)
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData error for git+https://github.com/StefaE/PVOptimize.git premature close
9 timing stage:rollbackFailedOptional Completed in 2ms
10 timing stage:runTopLevelLifecycles Completed in 6584ms
11 verbose stack Error: premature close
11 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
11 verbose stack     at PassThrough.emit (events.js:412:35)
11 verbose stack     at emitCloseNT (internal/streams/destroy.js:87:10)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
12 verbose cwd /opt/iobroker
13 verbose Linux 6.1.21-v8+
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "[https://github.com/StefaE/PVOptimize.git"](https://github.com/StefaE/PVOptimize.git%22)
15 verbose node v14.21.3
16 verbose npm  v6.14.18
17 error premature close
18 verbose exit [ 1, true ]
```

any ideas / hints / tips for this behavior?

thank you and best regards
Michael

**Comment by StefaE** [comment]
Hi Michael,
I'm not aware that I've programmed an adapter to anything ... so I'm also not sure what you did with what software in which environment :-). I've also not tried to package for any package manager. Not sure I can help here.
Stefan
